// yaha par hum kya karenge suspense kon karenge import
import { Suspense } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Loading from "./Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* yaha par hum kya karenge kii suspense ka use karke load karwa sakte hai page kon */}
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
